import {type Kysely, sql} from 'kysely'

export async function up(db: Kysely<any>): Promise<void> {
    await sql`
        create table users (
           id bigint generated by default as identity primary key,
           email text unique not null,
           username text  unique not null,
           password text  not null,
           first_name text not null,
           last_name text not null,
           is_admin boolean default false not null,
           created_at timestamp with time zone default now(),
           updated_at timestamp with time zone default now()
        )
    `.execute(db)
}

export async function down(db: Kysely<any>): Promise<void> {
	 await db.schema.dropTable('users').execute();
}
