import {type Kysely, sql} from 'kysely'

export async function up(db: Kysely<any>): Promise<void> {
	await sql`
        create table recipe_steps (
          id integer generated by default as identity primary key,
          recipe_id integer references recipes(id) on delete cascade,
          step_number integer not null,
          description text not null,
          created_at timestamp with time zone default now(),
          updated_at timestamp with time zone default now()
        )
    `.execute(db);
    await sql`create index recipe_steps_recipe_id_idx on recipe_steps (recipe_id)`.execute(db);
}

export async function down(db: Kysely<any>): Promise<void> {
    await db.schema.dropIndex('recipe_steps_recipe_id_idx').execute();
    await db.schema.dropTable('recipe_steps').execute();
}
