
services:
  db:
    image: supabase/postgres:15.8.1.040
    environment:
      POSTGRES_PASSWORD: postgres
    command: postgres -c config_file=/etc/postgresql/postgresql.conf 
    ports:
      - "5432:5432"

  cache:
    image: redis
    ports:
      - "6379:6379"