
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: food-swipe
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  cache:
    image: redis
    ports:
      - "6379:6379"