
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: food-swipe
    ports:
      - "5432:5432"

  cache:
    image: redis
    ports:
      - "6379:6379"