/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as mainRouteRouteImport } from './routes/(main)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as mainUsersRouteImport } from './routes/(main)/users'
import { Route as mainActivitiesRouteRouteImport } from './routes/(main)/activities/route'
import { Route as mainRecipesRecipesRouteImport } from './routes/(main)/recipes/recipes'
import { Route as mainRecipesMeasurementsRouteImport } from './routes/(main)/recipes/measurements'
import { Route as mainRecipesIngredientsRouteImport } from './routes/(main)/recipes/ingredients'
import { Route as mainRecipesRecipeIdRouteImport } from './routes/(main)/recipes/$recipeId'
import { Route as mainActivitiesRecipesUploadedRouteImport } from './routes/(main)/activities/recipes-uploaded'
import { Route as mainActivitiesLoginActivityRouteImport } from './routes/(main)/activities/login-activity'

const mainRouteRoute = mainRouteRouteImport.update({
  id: '/(main)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const mainUsersRoute = mainUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainActivitiesRouteRoute = mainActivitiesRouteRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainRecipesRecipesRoute = mainRecipesRecipesRouteImport.update({
  id: '/recipes/recipes',
  path: '/recipes/recipes',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainRecipesMeasurementsRoute = mainRecipesMeasurementsRouteImport.update({
  id: '/recipes/measurements',
  path: '/recipes/measurements',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainRecipesIngredientsRoute = mainRecipesIngredientsRouteImport.update({
  id: '/recipes/ingredients',
  path: '/recipes/ingredients',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainRecipesRecipeIdRoute = mainRecipesRecipeIdRouteImport.update({
  id: '/recipes/$recipeId',
  path: '/recipes/$recipeId',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainActivitiesRecipesUploadedRoute =
  mainActivitiesRecipesUploadedRouteImport.update({
    id: '/recipes-uploaded',
    path: '/recipes-uploaded',
    getParentRoute: () => mainActivitiesRouteRoute,
  } as any)
const mainActivitiesLoginActivityRoute =
  mainActivitiesLoginActivityRouteImport.update({
    id: '/login-activity',
    path: '/login-activity',
    getParentRoute: () => mainActivitiesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activities': typeof mainActivitiesRouteRouteWithChildren
  '/users': typeof mainUsersRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/': typeof AuthIndexRoute
  '/activities/login-activity': typeof mainActivitiesLoginActivityRoute
  '/activities/recipes-uploaded': typeof mainActivitiesRecipesUploadedRoute
  '/recipes/$recipeId': typeof mainRecipesRecipeIdRoute
  '/recipes/ingredients': typeof mainRecipesIngredientsRoute
  '/recipes/measurements': typeof mainRecipesMeasurementsRoute
  '/recipes/recipes': typeof mainRecipesRecipesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activities': typeof mainActivitiesRouteRouteWithChildren
  '/users': typeof mainUsersRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth': typeof AuthIndexRoute
  '/activities/login-activity': typeof mainActivitiesLoginActivityRoute
  '/activities/recipes-uploaded': typeof mainActivitiesRecipesUploadedRoute
  '/recipes/$recipeId': typeof mainRecipesRecipeIdRoute
  '/recipes/ingredients': typeof mainRecipesIngredientsRoute
  '/recipes/measurements': typeof mainRecipesMeasurementsRoute
  '/recipes/recipes': typeof mainRecipesRecipesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(main)': typeof mainRouteRouteWithChildren
  '/(main)/activities': typeof mainActivitiesRouteRouteWithChildren
  '/(main)/users': typeof mainUsersRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/': typeof AuthIndexRoute
  '/(main)/activities/login-activity': typeof mainActivitiesLoginActivityRoute
  '/(main)/activities/recipes-uploaded': typeof mainActivitiesRecipesUploadedRoute
  '/(main)/recipes/$recipeId': typeof mainRecipesRecipeIdRoute
  '/(main)/recipes/ingredients': typeof mainRecipesIngredientsRoute
  '/(main)/recipes/measurements': typeof mainRecipesMeasurementsRoute
  '/(main)/recipes/recipes': typeof mainRecipesRecipesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activities'
    | '/users'
    | '/auth/sign-in'
    | '/auth/'
    | '/activities/login-activity'
    | '/activities/recipes-uploaded'
    | '/recipes/$recipeId'
    | '/recipes/ingredients'
    | '/recipes/measurements'
    | '/recipes/recipes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activities'
    | '/users'
    | '/auth/sign-in'
    | '/auth'
    | '/activities/login-activity'
    | '/activities/recipes-uploaded'
    | '/recipes/$recipeId'
    | '/recipes/ingredients'
    | '/recipes/measurements'
    | '/recipes/recipes'
  id:
    | '__root__'
    | '/'
    | '/(main)'
    | '/(main)/activities'
    | '/(main)/users'
    | '/auth/sign-in'
    | '/auth/'
    | '/(main)/activities/login-activity'
    | '/(main)/activities/recipes-uploaded'
    | '/(main)/recipes/$recipeId'
    | '/(main)/recipes/ingredients'
    | '/(main)/recipes/measurements'
    | '/(main)/recipes/recipes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  mainRouteRoute: typeof mainRouteRouteWithChildren
  AuthSignInRoute: typeof AuthSignInRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(main)': {
      id: '/(main)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof mainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/users': {
      id: '/(main)/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof mainUsersRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/activities': {
      id: '/(main)/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof mainActivitiesRouteRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/recipes/recipes': {
      id: '/(main)/recipes/recipes'
      path: '/recipes/recipes'
      fullPath: '/recipes/recipes'
      preLoaderRoute: typeof mainRecipesRecipesRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/recipes/measurements': {
      id: '/(main)/recipes/measurements'
      path: '/recipes/measurements'
      fullPath: '/recipes/measurements'
      preLoaderRoute: typeof mainRecipesMeasurementsRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/recipes/ingredients': {
      id: '/(main)/recipes/ingredients'
      path: '/recipes/ingredients'
      fullPath: '/recipes/ingredients'
      preLoaderRoute: typeof mainRecipesIngredientsRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/recipes/$recipeId': {
      id: '/(main)/recipes/$recipeId'
      path: '/recipes/$recipeId'
      fullPath: '/recipes/$recipeId'
      preLoaderRoute: typeof mainRecipesRecipeIdRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/activities/recipes-uploaded': {
      id: '/(main)/activities/recipes-uploaded'
      path: '/recipes-uploaded'
      fullPath: '/activities/recipes-uploaded'
      preLoaderRoute: typeof mainActivitiesRecipesUploadedRouteImport
      parentRoute: typeof mainActivitiesRouteRoute
    }
    '/(main)/activities/login-activity': {
      id: '/(main)/activities/login-activity'
      path: '/login-activity'
      fullPath: '/activities/login-activity'
      preLoaderRoute: typeof mainActivitiesLoginActivityRouteImport
      parentRoute: typeof mainActivitiesRouteRoute
    }
  }
}

interface mainActivitiesRouteRouteChildren {
  mainActivitiesLoginActivityRoute: typeof mainActivitiesLoginActivityRoute
  mainActivitiesRecipesUploadedRoute: typeof mainActivitiesRecipesUploadedRoute
}

const mainActivitiesRouteRouteChildren: mainActivitiesRouteRouteChildren = {
  mainActivitiesLoginActivityRoute: mainActivitiesLoginActivityRoute,
  mainActivitiesRecipesUploadedRoute: mainActivitiesRecipesUploadedRoute,
}

const mainActivitiesRouteRouteWithChildren =
  mainActivitiesRouteRoute._addFileChildren(mainActivitiesRouteRouteChildren)

interface mainRouteRouteChildren {
  mainActivitiesRouteRoute: typeof mainActivitiesRouteRouteWithChildren
  mainUsersRoute: typeof mainUsersRoute
  mainRecipesRecipeIdRoute: typeof mainRecipesRecipeIdRoute
  mainRecipesIngredientsRoute: typeof mainRecipesIngredientsRoute
  mainRecipesMeasurementsRoute: typeof mainRecipesMeasurementsRoute
  mainRecipesRecipesRoute: typeof mainRecipesRecipesRoute
}

const mainRouteRouteChildren: mainRouteRouteChildren = {
  mainActivitiesRouteRoute: mainActivitiesRouteRouteWithChildren,
  mainUsersRoute: mainUsersRoute,
  mainRecipesRecipeIdRoute: mainRecipesRecipeIdRoute,
  mainRecipesIngredientsRoute: mainRecipesIngredientsRoute,
  mainRecipesMeasurementsRoute: mainRecipesMeasurementsRoute,
  mainRecipesRecipesRoute: mainRecipesRecipesRoute,
}

const mainRouteRouteWithChildren = mainRouteRoute._addFileChildren(
  mainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  mainRouteRoute: mainRouteRouteWithChildren,
  AuthSignInRoute: AuthSignInRoute,
  AuthIndexRoute: AuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
