version: "3.9"

services:
  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    restart: no
    environment:
      - DATABASE_URL=${DATABASE_URL} # Use an environment variable for DATABASE_URL
    command: bun run migrate
