import {
  boolean,
  bigint,
  text,
  doublePrecision,
  numeric,
  timestamp,
  pgView,
  integer,
} from "drizzle-orm/pg-core";

export const pgStatStatements = pgView("pg_stat_statements", {
  userid: integer("userid"),
  dbid: integer("dbid"),
  toplevel: boolean("toplevel"),
  queryid: bigint("queryid", { mode: "number" }),
  query: text("query"),
  plans: bigint("plans", { mode: "number" }),
  totalPlanTime: doublePrecision("total_plan_time"),
  minPlanTime: doublePrecision("min_plan_time"),
  maxPlanTime: doublePrecision("max_plan_time"),
  meanPlanTime: doublePrecision("mean_plan_time"),
  stddevPlanTime: doublePrecision("stddev_plan_time"),
  calls: bigint("calls", { mode: "number" }),
  totalExecTime: doublePrecision("total_exec_time"),
  minExecTime: doublePrecision("min_exec_time"),
  maxExecTime: doublePrecision("max_exec_time"),
  meanExecTime: doublePrecision("mean_exec_time"),
  stddevExecTime: doublePrecision("stddev_exec_time"),
  rows: bigint("rows", { mode: "number" }),
  sharedBlksHit: bigint("shared_blks_hit", { mode: "number" }),
  sharedBlksRead: bigint("shared_blks_read", { mode: "number" }),
  sharedBlksDirtied: bigint("shared_blks_dirtied", { mode: "number" }),
  sharedBlksWritten: bigint("shared_blks_written", { mode: "number" }),
  localBlksHit: bigint("local_blks_hit", { mode: "number" }),
  localBlksRead: bigint("local_blks_read", { mode: "number" }),
  localBlksDirtied: bigint("local_blks_dirtied", { mode: "number" }),
  localBlksWritten: bigint("local_blks_written", { mode: "number" }),
  tempBlksRead: bigint("temp_blks_read", { mode: "number" }),
  tempBlksWritten: bigint("temp_blks_written", { mode: "number" }),
  // sharedBlkReadTime: doublePrecision('shared_blk_read_time'),
  // sharedBlkWriteTime: doublePrecision("shared_blk_write_time"),
  // localBlkReadTime: doublePrecision("local_blk_read_time"),
  // localBlkWriteTime: doublePrecision("local_blk_write_time"),
  tempBlkReadTime: doublePrecision("temp_blk_read_time"),
  tempBlkWriteTime: doublePrecision("temp_blk_write_time"),
  walRecords: bigint("wal_records", { mode: "number" }),
  walFpi: bigint("wal_fpi", { mode: "number" }),
  walBytes: numeric("wal_bytes"),
  jitFunctions: bigint("jit_functions", { mode: "number" }),
  jitGenerationTime: doublePrecision("jit_generation_time"),
  jitInliningCount: bigint("jit_inlining_count", { mode: "number" }),
  jitInliningTime: doublePrecision("jit_inlining_time"),
  jitOptimizationCount: bigint("jit_optimization_count", { mode: "number" }),
  jitOptimizationTime: doublePrecision("jit_optimization_time"),
  jitEmissionCount: bigint("jit_emission_count", { mode: "number" }),
  jitEmissionTime: doublePrecision("jit_emission_time"),
  // jitDeformCount: bigint("jit_deform_count", { mode: "number" }),
  // jitDeformTime: doublePrecision("jit_deform_time"),
  // statsSince: timestamp("stats_since", { withTimezone: true }),
  // minmaxStatsSince: timestamp("minmax_stats_since", { withTimezone: true }),
}).existing();
