
export const lorem = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget tempor nunc. Vivamus sagittis justo quis faucibus iaculis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam urna neque, ultricies lacinia convallis non, dapibus sit amet turpis. Integer convallis varius suscipit. Vestibulum eget odio imperdiet, dignissim tellus eu, elementum risus. In hac habitasse platea dictumst. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

Duis sodales ex eget nibh maximus, at consequat tellus tempor. Suspendisse potenti. Aenean condimentum, risus quis egestas rhoncus, ligula turpis luctus est, a viverra nisl metus et enim. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas dictum nibh libero, sed rutrum turpis venenatis eu. Integer nibh purus, lacinia nec vestibulum ut, blandit ut quam. Duis at dolor pulvinar, rutrum dui sit amet, tincidunt urna.

Suspendisse tincidunt purus et mauris gravida, eget fermentum arcu accumsan. Praesent faucibus diam iaculis est ornare bibendum. Maecenas ac enim convallis, maximus urna nec, laoreet ante. Nunc congue mauris vel erat fermentum bibendum. Vestibulum vel aliquam erat, laoreet consequat mauris. Integer facilisis et lectus vitae consequat. Pellentesque tempus blandit porttitor. Sed ut semper nunc, in lacinia sapien. Quisque tincidunt aliquet tortor. Sed scelerisque nibh vitae velit auctor, eu euismod nunc euismod. Sed rutrum ullamcorper gravida.

Cras ornare non turpis vitae semper. Phasellus ut interdum magna, a elementum ante. Phasellus molestie consequat quam, ac interdum nisl fringilla suscipit. Nunc ultricies enim libero, et scelerisque nibh accumsan quis. Integer ullamcorper sapien ante, sed eleifend diam rhoncus eu. Fusce vitae orci non nibh pharetra congue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed eu fermentum magna, eget suscipit massa. Quisque et libero neque. Proin faucibus erat non laoreet faucibus. In ultrices at felis sit amet dictum. Vestibulum faucibus sapien sit amet dignissim imperdiet. Duis vulputate elit ut mauris sodales, quis cursus arcu ultrices. Integer in turpis egestas, faucibus nibh ut, pulvinar massa.

Donec eu nulla massa. Mauris venenatis ex ipsum, sit amet venenatis urna tristique quis. Suspendisse vel imperdiet elit, et rutrum risus. Curabitur ac risus quam. Donec tristique tortor a ligula dapibus ullamcorper. Nam dapibus purus turpis, in consequat ligula posuere eget. Donec lacinia semper diam. Etiam euismod ipsum vitae ex aliquet, sit amet gravida nunc faucibus. Nulla laoreet ac justo vel dictum. Donec ac eros consectetur, sodales sapien id, tincidunt dui. Fusce sed nibh venenatis, tristique turpis eu, posuere eros. Etiam semper, risus non euismod pharetra, quam leo tincidunt dolor, ut accumsan quam turpis eget ex.`