// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file followers/v1/followers.proto (package followers.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../buf/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file followers/v1/followers.proto.
 */
export const file_followers_v1_followers: GenFile = /*@__PURE__*/
  fileDesc("Chxmb2xsb3dlcnMvdjEvZm9sbG93ZXJzLnByb3RvEgxmb2xsb3dlcnMudjEiSQoNRm9sbG93UmVxdWVzdBIZCgd1c2VyX2lkGAEgASgJQgi6SAVyA7ABARIdCgtmb2xsb3dlcl9pZBgCIAEoCUIIukgFcgOwAQEiEAoORm9sbG93UmVzcG9uc2UiMAoTR2V0Rm9sbG93ZXJzUmVxdWVzdBIZCgd1c2VyX2lkGAEgASgJQgi6SAVyA7ABASIpChRHZXRGb2xsb3dlcnNSZXNwb25zZRIRCglmb2xsb3dlcnMYASADKAkiMAoTR2V0Rm9sbG93aW5nUmVxdWVzdBIZCgd1c2VyX2lkGAEgASgJQgi6SAVyA7ABASIpChRHZXRGb2xsb3dpbmdSZXNwb25zZRIRCglmb2xsb3dpbmcYASADKAkyigIKD0ZvbGxvd2VyU2VydmljZRJFCgZGb2xsb3cSGy5mb2xsb3dlcnMudjEuRm9sbG93UmVxdWVzdBocLmZvbGxvd2Vycy52MS5Gb2xsb3dSZXNwb25zZSIAElcKDEdldEZvbGxvd2VycxIhLmZvbGxvd2Vycy52MS5HZXRGb2xsb3dlcnNSZXF1ZXN0GiIuZm9sbG93ZXJzLnYxLkdldEZvbGxvd2Vyc1Jlc3BvbnNlIgASVwoMR2V0Rm9sbG93aW5nEiEuZm9sbG93ZXJzLnYxLkdldEZvbGxvd2luZ1JlcXVlc3QaIi5mb2xsb3dlcnMudjEuR2V0Rm9sbG93aW5nUmVzcG9uc2UiAEKsAQoQY29tLmZvbGxvd2Vycy52MUIORm9sbG93ZXJzUHJvdG9QAVo3Z2l0aHViLmNvbS9mb29kLXN3aXBlL2dlbi9ncnBjL2ZvbGxvd2Vycy92MTtmb2xsb3dlcnN2MaICA0ZYWKoCDEZvbGxvd2Vycy5WMcoCDEZvbGxvd2Vyc1xWMeICGEZvbGxvd2Vyc1xWMVxHUEJNZXRhZGF0YeoCDUZvbGxvd2Vyczo6VjFiBnByb3RvMw", [file_buf_validate_validate]);

/**
 * @generated from message followers.v1.FollowRequest
 */
export type FollowRequest = Message<"followers.v1.FollowRequest"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * @generated from field: string follower_id = 2;
   */
  followerId: string;
};

/**
 * Describes the message followers.v1.FollowRequest.
 * Use `create(FollowRequestSchema)` to create a new message.
 */
export const FollowRequestSchema: GenMessage<FollowRequest> = /*@__PURE__*/
  messageDesc(file_followers_v1_followers, 0);

/**
 * @generated from message followers.v1.FollowResponse
 */
export type FollowResponse = Message<"followers.v1.FollowResponse"> & {
};

/**
 * Describes the message followers.v1.FollowResponse.
 * Use `create(FollowResponseSchema)` to create a new message.
 */
export const FollowResponseSchema: GenMessage<FollowResponse> = /*@__PURE__*/
  messageDesc(file_followers_v1_followers, 1);

/**
 * @generated from message followers.v1.GetFollowersRequest
 */
export type GetFollowersRequest = Message<"followers.v1.GetFollowersRequest"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;
};

/**
 * Describes the message followers.v1.GetFollowersRequest.
 * Use `create(GetFollowersRequestSchema)` to create a new message.
 */
export const GetFollowersRequestSchema: GenMessage<GetFollowersRequest> = /*@__PURE__*/
  messageDesc(file_followers_v1_followers, 2);

/**
 * @generated from message followers.v1.GetFollowersResponse
 */
export type GetFollowersResponse = Message<"followers.v1.GetFollowersResponse"> & {
  /**
   * @generated from field: repeated string followers = 1;
   */
  followers: string[];
};

/**
 * Describes the message followers.v1.GetFollowersResponse.
 * Use `create(GetFollowersResponseSchema)` to create a new message.
 */
export const GetFollowersResponseSchema: GenMessage<GetFollowersResponse> = /*@__PURE__*/
  messageDesc(file_followers_v1_followers, 3);

/**
 * @generated from message followers.v1.GetFollowingRequest
 */
export type GetFollowingRequest = Message<"followers.v1.GetFollowingRequest"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;
};

/**
 * Describes the message followers.v1.GetFollowingRequest.
 * Use `create(GetFollowingRequestSchema)` to create a new message.
 */
export const GetFollowingRequestSchema: GenMessage<GetFollowingRequest> = /*@__PURE__*/
  messageDesc(file_followers_v1_followers, 4);

/**
 * @generated from message followers.v1.GetFollowingResponse
 */
export type GetFollowingResponse = Message<"followers.v1.GetFollowingResponse"> & {
  /**
   * @generated from field: repeated string following = 1;
   */
  following: string[];
};

/**
 * Describes the message followers.v1.GetFollowingResponse.
 * Use `create(GetFollowingResponseSchema)` to create a new message.
 */
export const GetFollowingResponseSchema: GenMessage<GetFollowingResponse> = /*@__PURE__*/
  messageDesc(file_followers_v1_followers, 5);

/**
 * @generated from service followers.v1.FollowerService
 */
export const FollowerService: GenService<{
  /**
   * @generated from rpc followers.v1.FollowerService.Follow
   */
  follow: {
    methodKind: "unary";
    input: typeof FollowRequestSchema;
    output: typeof FollowResponseSchema;
  },
  /**
   * @generated from rpc followers.v1.FollowerService.GetFollowers
   */
  getFollowers: {
    methodKind: "unary";
    input: typeof GetFollowersRequestSchema;
    output: typeof GetFollowersResponseSchema;
  },
  /**
   * @generated from rpc followers.v1.FollowerService.GetFollowing
   */
  getFollowing: {
    methodKind: "unary";
    input: typeof GetFollowingRequestSchema;
    output: typeof GetFollowingResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_followers_v1_followers, 0);

