// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file followers/v1/follower.proto (package followers.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../buf/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file followers/v1/follower.proto.
 */
export const file_followers_v1_follower: GenFile = /*@__PURE__*/
  fileDesc("Chtmb2xsb3dlcnMvdjEvZm9sbG93ZXIucHJvdG8SDGZvbGxvd2Vycy52MSJJCg1Gb2xsb3dSZXF1ZXN0EhkKB3VzZXJfaWQYASABKAlCCLpIBXIDsAEBEh0KC2ZvbGxvd2VyX2lkGAIgASgJQgi6SAVyA7ABASIQCg5Gb2xsb3dSZXNwb25zZSIwChNHZXRGb2xsb3dlcnNSZXF1ZXN0EhkKB3VzZXJfaWQYASABKAlCCLpIBXIDsAEBIikKFEdldEZvbGxvd2Vyc1Jlc3BvbnNlEhEKCWZvbGxvd2VycxgBIAMoCSIwChNHZXRGb2xsb3dpbmdSZXF1ZXN0EhkKB3VzZXJfaWQYASABKAlCCLpIBXIDsAEBIikKFEdldEZvbGxvd2luZ1Jlc3BvbnNlEhEKCWZvbGxvd2luZxgBIAMoCTKKAgoPRm9sbG93ZXJTZXJ2aWNlEkUKBkZvbGxvdxIbLmZvbGxvd2Vycy52MS5Gb2xsb3dSZXF1ZXN0GhwuZm9sbG93ZXJzLnYxLkZvbGxvd1Jlc3BvbnNlIgASVwoMR2V0Rm9sbG93ZXJzEiEuZm9sbG93ZXJzLnYxLkdldEZvbGxvd2Vyc1JlcXVlc3QaIi5mb2xsb3dlcnMudjEuR2V0Rm9sbG93ZXJzUmVzcG9uc2UiABJXCgxHZXRGb2xsb3dpbmcSIS5mb2xsb3dlcnMudjEuR2V0Rm9sbG93aW5nUmVxdWVzdBoiLmZvbGxvd2Vycy52MS5HZXRGb2xsb3dpbmdSZXNwb25zZSIAQqYBChBjb20uZm9sbG93ZXJzLnYxQg1Gb2xsb3dlclByb3RvUAFaMmdpdGh1Yi5jb20vZm9vZC1zd2lwZS9nZW4vZm9sbG93ZXJzL3YxO2ZvbGxvd2Vyc3YxogIDRlhYqgIMRm9sbG93ZXJzLlYxygIMRm9sbG93ZXJzXFYx4gIYRm9sbG93ZXJzXFYxXEdQQk1ldGFkYXRh6gINRm9sbG93ZXJzOjpWMWIGcHJvdG8z", [file_buf_validate_validate]);

/**
 * @generated from message followers.v1.FollowRequest
 */
export type FollowRequest = Message<"followers.v1.FollowRequest"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * @generated from field: string follower_id = 2;
   */
  followerId: string;
};

/**
 * Describes the message followers.v1.FollowRequest.
 * Use `create(FollowRequestSchema)` to create a new message.
 */
export const FollowRequestSchema: GenMessage<FollowRequest> = /*@__PURE__*/
  messageDesc(file_followers_v1_follower, 0);

/**
 * @generated from message followers.v1.FollowResponse
 */
export type FollowResponse = Message<"followers.v1.FollowResponse"> & {
};

/**
 * Describes the message followers.v1.FollowResponse.
 * Use `create(FollowResponseSchema)` to create a new message.
 */
export const FollowResponseSchema: GenMessage<FollowResponse> = /*@__PURE__*/
  messageDesc(file_followers_v1_follower, 1);

/**
 * @generated from message followers.v1.GetFollowersRequest
 */
export type GetFollowersRequest = Message<"followers.v1.GetFollowersRequest"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;
};

/**
 * Describes the message followers.v1.GetFollowersRequest.
 * Use `create(GetFollowersRequestSchema)` to create a new message.
 */
export const GetFollowersRequestSchema: GenMessage<GetFollowersRequest> = /*@__PURE__*/
  messageDesc(file_followers_v1_follower, 2);

/**
 * @generated from message followers.v1.GetFollowersResponse
 */
export type GetFollowersResponse = Message<"followers.v1.GetFollowersResponse"> & {
  /**
   * @generated from field: repeated string followers = 1;
   */
  followers: string[];
};

/**
 * Describes the message followers.v1.GetFollowersResponse.
 * Use `create(GetFollowersResponseSchema)` to create a new message.
 */
export const GetFollowersResponseSchema: GenMessage<GetFollowersResponse> = /*@__PURE__*/
  messageDesc(file_followers_v1_follower, 3);

/**
 * @generated from message followers.v1.GetFollowingRequest
 */
export type GetFollowingRequest = Message<"followers.v1.GetFollowingRequest"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;
};

/**
 * Describes the message followers.v1.GetFollowingRequest.
 * Use `create(GetFollowingRequestSchema)` to create a new message.
 */
export const GetFollowingRequestSchema: GenMessage<GetFollowingRequest> = /*@__PURE__*/
  messageDesc(file_followers_v1_follower, 4);

/**
 * @generated from message followers.v1.GetFollowingResponse
 */
export type GetFollowingResponse = Message<"followers.v1.GetFollowingResponse"> & {
  /**
   * @generated from field: repeated string following = 1;
   */
  following: string[];
};

/**
 * Describes the message followers.v1.GetFollowingResponse.
 * Use `create(GetFollowingResponseSchema)` to create a new message.
 */
export const GetFollowingResponseSchema: GenMessage<GetFollowingResponse> = /*@__PURE__*/
  messageDesc(file_followers_v1_follower, 5);

/**
 * @generated from service followers.v1.FollowerService
 */
export const FollowerService: GenService<{
  /**
   * @generated from rpc followers.v1.FollowerService.Follow
   */
  follow: {
    methodKind: "unary";
    input: typeof FollowRequestSchema;
    output: typeof FollowResponseSchema;
  },
  /**
   * @generated from rpc followers.v1.FollowerService.GetFollowers
   */
  getFollowers: {
    methodKind: "unary";
    input: typeof GetFollowersRequestSchema;
    output: typeof GetFollowersResponseSchema;
  },
  /**
   * @generated from rpc followers.v1.FollowerService.GetFollowing
   */
  getFollowing: {
    methodKind: "unary";
    input: typeof GetFollowingRequestSchema;
    output: typeof GetFollowingResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_followers_v1_follower, 0);

