import {type Kysely, sql} from 'kysely'

export async function up(db: Kysely<any>): Promise<void> {
	await sql`
        create table recipes (
         id bigint generated by default as identity primary key,
         title varchar(255) unique not null,
         description text,
         prep_time integer,
         servings integer,
         calories integer,
         is_published boolean default false,
         created_at timestamp with time zone default now(),
         updated_at timestamp with time zone default now()
        )
    `.execute(db);

    await db.schema.createIndex('recipes_is_published_idx')
        .on('recipes')
        .column('is_published')
        .execute();
}

export async function down(db: Kysely<any>): Promise<void> {
    await db.schema.dropTable('recipes').execute();
}
