import {type Kysely, sql} from 'kysely'

export async function up(db: Kysely<any>): Promise<void> {
	await sql`
        create table files (
           id bigint generated by default as identity primary key,
           user_id bigint references users(id) on delete cascade,
           filename varchar(255) not null unique,
           type varchar(255) not null,
           is_public boolean default false,
           created_at timestamp with time zone default now(),
           updated_at timestamp with time zone default now()
        )
    `.execute(db);
    await sql`create index files_is_public_idx on files (is_public)`.execute(db);
    await sql`create index files_user_id_idx on files (user_id)`.execute(db);
}

export async function down(db: Kysely<any>): Promise<void> {
    await db.schema.dropIndex('files_is_public_idx').execute();
    await db.schema.dropIndex('files_user_id_idx').execute();
    await db.schema.dropTable('files').execute();
}
