create table recipes (
    id bigint generated by default as identity primary key,
    title varchar(255) unique not null,
    description text,
    prep_time integer,
    servings integer,
    calories integer,
    is_published boolean default false,
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone default now()
);

create index recipes_is_published_idx on recipes (is_published);