create table recipe_steps (
    id bigint generated by default as identity primary key,
    recipe_id bigint references recipes(id) on delete cascade,
    step_number integer not null,
    description text not null,
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone default now()
);

create index recipe_steps_recipe_id_idx on recipe_steps (recipe_id);