// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file food-swipe/v1/common.proto (package foodswipe.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file food-swipe/v1/common.proto.
 */
export const file_food_swipe_v1_common: GenFile = /*@__PURE__*/
  fileDesc("Chpmb29kLXN3aXBlL3YxL2NvbW1vbi5wcm90bxIMZm9vZHN3aXBlLnYxIlgKClBhZ2luYXRpb24SEAoIcGVyX3BhZ2UYASABKA0SEwoLdG90YWxfcGFnZXMYAiABKA0SFAoMY3VycmVudF9wYWdlGAMgASgNEg0KBXRvdGFsGAQgASgNQqoBChBjb20uZm9vZHN3aXBlLnYxQgtDb21tb25Qcm90b1ABWjhnaXRodWIuY29tL2Zvb2Qtc3dpcGUvZ2VuL2dycGMvZm9vZC1zd2lwZS92MTtmb29kc3dpcGV2MaICA0ZYWKoCDEZvb2Rzd2lwZS5WMcoCDEZvb2Rzd2lwZVxWMeICGEZvb2Rzd2lwZVxWMVxHUEJNZXRhZGF0YeoCDUZvb2Rzd2lwZTo6VjFiBnByb3RvMw");

/**
 * @generated from message foodswipe.v1.Pagination
 */
export type Pagination = Message<"foodswipe.v1.Pagination"> & {
  /**
   * @generated from field: uint32 per_page = 1;
   */
  perPage: number;

  /**
   * @generated from field: uint32 total_pages = 2;
   */
  totalPages: number;

  /**
   * @generated from field: uint32 current_page = 3;
   */
  currentPage: number;

  /**
   * @generated from field: uint32 total = 4;
   */
  total: number;
};

/**
 * Describes the message foodswipe.v1.Pagination.
 * Use `create(PaginationSchema)` to create a new message.
 */
export const PaginationSchema: GenMessage<Pagination> = /*@__PURE__*/
  messageDesc(file_food_swipe_v1_common, 0);

