// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file food-swipe/v1/followers.proto (package foodswipe.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../buf/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file food-swipe/v1/followers.proto.
 */
export const file_food_swipe_v1_followers: GenFile = /*@__PURE__*/
  fileDesc("Ch1mb29kLXN3aXBlL3YxL2ZvbGxvd2Vycy5wcm90bxIMZm9vZHN3aXBlLnYxIkkKDUZvbGxvd1JlcXVlc3QSGQoHdXNlcl9pZBgBIAEoCUIIukgFcgOwAQESHQoLZm9sbG93ZXJfaWQYAiABKAlCCLpIBXIDsAEBIhAKDkZvbGxvd1Jlc3BvbnNlIjAKE0dldEZvbGxvd2Vyc1JlcXVlc3QSGQoHdXNlcl9pZBgBIAEoCUIIukgFcgOwAQEiKQoUR2V0Rm9sbG93ZXJzUmVzcG9uc2USEQoJZm9sbG93ZXJzGAEgAygJIjAKE0dldEZvbGxvd2luZ1JlcXVlc3QSGQoHdXNlcl9pZBgBIAEoCUIIukgFcgOwAQEiKQoUR2V0Rm9sbG93aW5nUmVzcG9uc2USEQoJZm9sbG93aW5nGAEgAygJMooCCg9Gb2xsb3dlclNlcnZpY2USRQoGRm9sbG93EhsuZm9vZHN3aXBlLnYxLkZvbGxvd1JlcXVlc3QaHC5mb29kc3dpcGUudjEuRm9sbG93UmVzcG9uc2UiABJXCgxHZXRGb2xsb3dlcnMSIS5mb29kc3dpcGUudjEuR2V0Rm9sbG93ZXJzUmVxdWVzdBoiLmZvb2Rzd2lwZS52MS5HZXRGb2xsb3dlcnNSZXNwb25zZSIAElcKDEdldEZvbGxvd2luZxIhLmZvb2Rzd2lwZS52MS5HZXRGb2xsb3dpbmdSZXF1ZXN0GiIuZm9vZHN3aXBlLnYxLkdldEZvbGxvd2luZ1Jlc3BvbnNlIgBCrQEKEGNvbS5mb29kc3dpcGUudjFCDkZvbGxvd2Vyc1Byb3RvUAFaOGdpdGh1Yi5jb20vZm9vZC1zd2lwZS9nZW4vZ3JwYy9mb29kLXN3aXBlL3YxO2Zvb2Rzd2lwZXYxogIDRlhYqgIMRm9vZHN3aXBlLlYxygIMRm9vZHN3aXBlXFYx4gIYRm9vZHN3aXBlXFYxXEdQQk1ldGFkYXRh6gINRm9vZHN3aXBlOjpWMWIGcHJvdG8z", [file_buf_validate_validate]);

/**
 * @generated from message foodswipe.v1.FollowRequest
 */
export type FollowRequest = Message<"foodswipe.v1.FollowRequest"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * @generated from field: string follower_id = 2;
   */
  followerId: string;
};

/**
 * Describes the message foodswipe.v1.FollowRequest.
 * Use `create(FollowRequestSchema)` to create a new message.
 */
export const FollowRequestSchema: GenMessage<FollowRequest> = /*@__PURE__*/
  messageDesc(file_food_swipe_v1_followers, 0);

/**
 * @generated from message foodswipe.v1.FollowResponse
 */
export type FollowResponse = Message<"foodswipe.v1.FollowResponse"> & {
};

/**
 * Describes the message foodswipe.v1.FollowResponse.
 * Use `create(FollowResponseSchema)` to create a new message.
 */
export const FollowResponseSchema: GenMessage<FollowResponse> = /*@__PURE__*/
  messageDesc(file_food_swipe_v1_followers, 1);

/**
 * @generated from message foodswipe.v1.GetFollowersRequest
 */
export type GetFollowersRequest = Message<"foodswipe.v1.GetFollowersRequest"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;
};

/**
 * Describes the message foodswipe.v1.GetFollowersRequest.
 * Use `create(GetFollowersRequestSchema)` to create a new message.
 */
export const GetFollowersRequestSchema: GenMessage<GetFollowersRequest> = /*@__PURE__*/
  messageDesc(file_food_swipe_v1_followers, 2);

/**
 * @generated from message foodswipe.v1.GetFollowersResponse
 */
export type GetFollowersResponse = Message<"foodswipe.v1.GetFollowersResponse"> & {
  /**
   * @generated from field: repeated string followers = 1;
   */
  followers: string[];
};

/**
 * Describes the message foodswipe.v1.GetFollowersResponse.
 * Use `create(GetFollowersResponseSchema)` to create a new message.
 */
export const GetFollowersResponseSchema: GenMessage<GetFollowersResponse> = /*@__PURE__*/
  messageDesc(file_food_swipe_v1_followers, 3);

/**
 * @generated from message foodswipe.v1.GetFollowingRequest
 */
export type GetFollowingRequest = Message<"foodswipe.v1.GetFollowingRequest"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;
};

/**
 * Describes the message foodswipe.v1.GetFollowingRequest.
 * Use `create(GetFollowingRequestSchema)` to create a new message.
 */
export const GetFollowingRequestSchema: GenMessage<GetFollowingRequest> = /*@__PURE__*/
  messageDesc(file_food_swipe_v1_followers, 4);

/**
 * @generated from message foodswipe.v1.GetFollowingResponse
 */
export type GetFollowingResponse = Message<"foodswipe.v1.GetFollowingResponse"> & {
  /**
   * @generated from field: repeated string following = 1;
   */
  following: string[];
};

/**
 * Describes the message foodswipe.v1.GetFollowingResponse.
 * Use `create(GetFollowingResponseSchema)` to create a new message.
 */
export const GetFollowingResponseSchema: GenMessage<GetFollowingResponse> = /*@__PURE__*/
  messageDesc(file_food_swipe_v1_followers, 5);

/**
 * @generated from service foodswipe.v1.FollowerService
 */
export const FollowerService: GenService<{
  /**
   * @generated from rpc foodswipe.v1.FollowerService.Follow
   */
  follow: {
    methodKind: "unary";
    input: typeof FollowRequestSchema;
    output: typeof FollowResponseSchema;
  },
  /**
   * @generated from rpc foodswipe.v1.FollowerService.GetFollowers
   */
  getFollowers: {
    methodKind: "unary";
    input: typeof GetFollowersRequestSchema;
    output: typeof GetFollowersResponseSchema;
  },
  /**
   * @generated from rpc foodswipe.v1.FollowerService.GetFollowing
   */
  getFollowing: {
    methodKind: "unary";
    input: typeof GetFollowingRequestSchema;
    output: typeof GetFollowingResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_food_swipe_v1_followers, 0);

