// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file food-swipe/v1/user.proto (package foodswipe.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../buf/validate/validate_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file food-swipe/v1/user.proto.
 */
export const file_food_swipe_v1_user: GenFile = /*@__PURE__*/
  fileDesc("Chhmb29kLXN3aXBlL3YxL3VzZXIucHJvdG8SDGZvb2Rzd2lwZS52MSKhAwoEVXNlchIUCgJpZBgBIAEoCUIIukgFcgOwAQESDAoEbmFtZRgCIAEoCRINCgVlbWFpbBgDIAEoCRIWCg5lbWFpbF92ZXJpZmllZBgEIAEoCBISCgVpbWFnZRgFIAEoCUgAiAEBEhAKCHVzZXJuYW1lGAYgASgJEh0KEGRpc3BsYXlfdXNlcm5hbWUYByABKAlIAYgBARIMCgRyb2xlGAggASgJEg4KBmJhbm5lZBgJIAEoCBIXCgpiYW5fcmVhc29uGAogASgJSAKIAQESNAoLYmFuX2V4cGlyZXMYCyABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wSAOIAQESLgoKY3JlYXRlZF9hdBgMIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASLgoKdXBkYXRlZF9hdBgNIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXBCCAoGX2ltYWdlQhMKEV9kaXNwbGF5X3VzZXJuYW1lQg0KC19iYW5fcmVhc29uQg4KDF9iYW5fZXhwaXJlcyIqChJHZXRVc2VyQnlJZFJlcXVlc3QSFAoCaWQYASABKAlCCLpIBXIDsAEBIjcKE0dldFVzZXJCeUlkUmVzcG9uc2USIAoEdXNlchgBIAEoCzISLmZvb2Rzd2lwZS52MS5Vc2VyMmEKC1VzZXJTZXJ2aWNlElIKC0dldFVzZXJCeUlkEiAuZm9vZHN3aXBlLnYxLkdldFVzZXJCeUlkUmVxdWVzdBohLmZvb2Rzd2lwZS52MS5HZXRVc2VyQnlJZFJlc3BvbnNlQqgBChBjb20uZm9vZHN3aXBlLnYxQglVc2VyUHJvdG9QAVo4Z2l0aHViLmNvbS9mb29kLXN3aXBlL2dlbi9ncnBjL2Zvb2Qtc3dpcGUvdjE7Zm9vZHN3aXBldjGiAgNGWFiqAgxGb29kc3dpcGUuVjHKAgxGb29kc3dpcGVcVjHiAhhGb29kc3dpcGVcVjFcR1BCTWV0YWRhdGHqAg1Gb29kc3dpcGU6OlYxYgZwcm90bzM", [file_buf_validate_validate, file_google_protobuf_timestamp]);

/**
 * @generated from message foodswipe.v1.User
 */
export type User = Message<"foodswipe.v1.User"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string email = 3;
   */
  email: string;

  /**
   * @generated from field: bool email_verified = 4;
   */
  emailVerified: boolean;

  /**
   * @generated from field: optional string image = 5;
   */
  image?: string;

  /**
   * @generated from field: string username = 6;
   */
  username: string;

  /**
   * @generated from field: optional string display_username = 7;
   */
  displayUsername?: string;

  /**
   * @generated from field: string role = 8;
   */
  role: string;

  /**
   * @generated from field: bool banned = 9;
   */
  banned: boolean;

  /**
   * @generated from field: optional string ban_reason = 10;
   */
  banReason?: string;

  /**
   * @generated from field: optional google.protobuf.Timestamp ban_expires = 11;
   */
  banExpires?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 12;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 13;
   */
  updatedAt?: Timestamp;
};

/**
 * Describes the message foodswipe.v1.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema: GenMessage<User> = /*@__PURE__*/
  messageDesc(file_food_swipe_v1_user, 0);

/**
 * @generated from message foodswipe.v1.GetUserByIdRequest
 */
export type GetUserByIdRequest = Message<"foodswipe.v1.GetUserByIdRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message foodswipe.v1.GetUserByIdRequest.
 * Use `create(GetUserByIdRequestSchema)` to create a new message.
 */
export const GetUserByIdRequestSchema: GenMessage<GetUserByIdRequest> = /*@__PURE__*/
  messageDesc(file_food_swipe_v1_user, 1);

/**
 * @generated from message foodswipe.v1.GetUserByIdResponse
 */
export type GetUserByIdResponse = Message<"foodswipe.v1.GetUserByIdResponse"> & {
  /**
   * @generated from field: foodswipe.v1.User user = 1;
   */
  user?: User;
};

/**
 * Describes the message foodswipe.v1.GetUserByIdResponse.
 * Use `create(GetUserByIdResponseSchema)` to create a new message.
 */
export const GetUserByIdResponseSchema: GenMessage<GetUserByIdResponse> = /*@__PURE__*/
  messageDesc(file_food_swipe_v1_user, 2);

/**
 * @generated from service foodswipe.v1.UserService
 */
export const UserService: GenService<{
  /**
   * @generated from rpc foodswipe.v1.UserService.GetUserById
   */
  getUserById: {
    methodKind: "unary";
    input: typeof GetUserByIdRequestSchema;
    output: typeof GetUserByIdResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_food_swipe_v1_user, 0);

