import { Colors } from "./colors";

export const recipeBookGradients = [
  {
    name: "Red",
    background: [Colors.red100, Colors.red200],
    backgroundDark: [Colors.red900, Colors.red800],
    text: Colors.red600,
    textDark: Colors.red300,
  },
  {
    name: "Teal",
    background: [Colors.teal100, Colors.teal200],
    backgroundDark: [Colors.teal900, Colors.teal800],
    text: Colors.teal600,
    textDark: Colors.teal300,
  },
  {
    name: "Purple",
    background: [Colors.purple100, Colors.purple200],
    backgroundDark: [Colors.purple900, Colors.purple800],
    text: Colors.purple600,
    textDark: Colors.purple300,
  },
  {
    name: "Yellow",
    background: [Colors.yellow100, Colors.yellow200],
    backgroundDark: [Colors.yellow900, Colors.yellow800],
    text: Colors.yellow600,
    textDark: Colors.yellow300,
  },
  {
    name: "Slate",
    background: [Colors.slate100, Colors.slate200],
    backgroundDark: [Colors.slate900, Colors.slate800],
    text: Colors.slate600,
    textDark: Colors.slate300,
  },
  {
    name: "Pink",
    background: [Colors.pink100, Colors.pink200],
    backgroundDark: [Colors.pink900, Colors.pink800],
    text: Colors.pink600,
    textDark: Colors.pink300,
  },
  {
    name: "Green",
    background: [Colors.green100, Colors.green200],
    backgroundDark: [Colors.green900, Colors.green800],
    text: Colors.green600,
    textDark: Colors.green300,
  },
  {
    name: "Indigo",
    background: [Colors.indigo100, Colors.indigo200],
    backgroundDark: [Colors.indigo900, Colors.indigo800],
    text: Colors.indigo600,
    textDark: Colors.indigo300,
  },
  {
    name: "Orange",
    background: [Colors.orange100, Colors.orange200],
    backgroundDark: [Colors.orange900, Colors.orange800],
    text: Colors.orange600,
    textDark: Colors.orange300,
  },
  {
    name: "Gray",
    background: [Colors.gray100, Colors.gray200],
    backgroundDark: [Colors.gray900, Colors.gray800],
    text: Colors.gray600,
    textDark: Colors.gray300,
  },
  {
    name: "Cyan",
    background: [Colors.cyan100, Colors.cyan200],
    backgroundDark: [Colors.cyan900, Colors.cyan800],
    text: Colors.cyan600,
    textDark: Colors.cyan300,
  },
  {
    name: "Fuchsia",
    background: [Colors.fuchsia100, Colors.fuchsia200],
    backgroundDark: [Colors.fuchsia900, Colors.fuchsia800],
    text: Colors.fuchsia600,
    textDark: Colors.fuchsia300,
  },
  {
    name: "Lime",
    background: [Colors.lime100, Colors.lime200],
    backgroundDark: [Colors.lime900, Colors.lime800],
    text: Colors.lime600,
    textDark: Colors.lime300,
  },
  {
    name: "Blue",
    background: [Colors.blue100, Colors.blue200],
    backgroundDark: [Colors.blue900, Colors.blue800],
    text: Colors.blue600,
    textDark: Colors.blue300,
  },
  {
    name: "Stone",
    background: [Colors.stone100, Colors.stone200],
    backgroundDark: [Colors.stone900, Colors.stone800],
    text: Colors.stone600,
    textDark: Colors.stone300,
  },
  {
    name: "Rose",
    background: [Colors.rose100, Colors.rose200],
    backgroundDark: [Colors.rose900, Colors.rose800],
    text: Colors.rose600,
    textDark: Colors.rose300,
  },
  {
    name: "Emerald",
    background: [Colors.emerald100, Colors.emerald200],
    backgroundDark: [Colors.emerald900, Colors.emerald800],
    text: Colors.emerald600,
    textDark: Colors.emerald300,
  },
  {
    name: "Violet",
    background: [Colors.violet100, Colors.violet200],
    backgroundDark: [Colors.violet900, Colors.violet800],
    text: Colors.violet600,
    textDark: Colors.violet300,
  },
  {
    name: "Amber",
    background: [Colors.amber100, Colors.amber200],
    backgroundDark: [Colors.amber900, Colors.amber800],
    text: Colors.amber600,
    textDark: Colors.amber300,
  },
  {
    name: "Sky",
    background: [Colors.sky100, Colors.sky200],
    backgroundDark: [Colors.sky900, Colors.sky800],
    text: Colors.sky600,
    textDark: Colors.sky300,
  },
  {
    name: "Zinc",
    background: [Colors.zinc100, Colors.zinc200],
    backgroundDark: [Colors.zinc900, Colors.zinc800],
    text: Colors.zinc600,
    textDark: Colors.zinc300,
  },
] as const;
