version: '3'

services:
  food-swipe-backend:
    image: ghcr.io/msvdaamen/food-swipe-admin-backend:latest
    container_name: food-swipe-admin-backend
    restart: always
    env_file: ".env"
    ports:
      - "127.0.0.1:3001:3001"
    deploy:
      update_config:
        parallelism: 1
        order: start-first