// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/food-swipe/internal/pkg/models/pagination"
	"github.com/food-swipe/internal/user/core/models"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewStorage creates a new instance of Storage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *Storage {
	mock := &Storage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

type Storage_Expecter struct {
	mock *mock.Mock
}

func (_m *Storage) EXPECT() *Storage_Expecter {
	return &Storage_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type Storage
func (_mock *Storage) CreateUser(ctx context.Context, params *models.CreateUserParams) (*models.User, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.CreateUserParams) (*models.User, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.CreateUserParams) *models.User); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *models.CreateUserParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Storage_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type Storage_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - params *models.CreateUserParams
func (_e *Storage_Expecter) CreateUser(ctx interface{}, params interface{}) *Storage_CreateUser_Call {
	return &Storage_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, params)}
}

func (_c *Storage_CreateUser_Call) Run(run func(ctx context.Context, params *models.CreateUserParams)) *Storage_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.CreateUserParams
		if args[1] != nil {
			arg1 = args[1].(*models.CreateUserParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Storage_CreateUser_Call) Return(user *models.User, err error) *Storage_CreateUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *Storage_CreateUser_Call) RunAndReturn(run func(ctx context.Context, params *models.CreateUserParams) (*models.User, error)) *Storage_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByEmail provides a mock function for the type Storage
func (_mock *Storage) GetUserByEmail(ctx context.Context, email string) (*models.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 *models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Storage_GetUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByEmail'
type Storage_GetUserByEmail_Call struct {
	*mock.Call
}

// GetUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *Storage_Expecter) GetUserByEmail(ctx interface{}, email interface{}) *Storage_GetUserByEmail_Call {
	return &Storage_GetUserByEmail_Call{Call: _e.mock.On("GetUserByEmail", ctx, email)}
}

func (_c *Storage_GetUserByEmail_Call) Run(run func(ctx context.Context, email string)) *Storage_GetUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Storage_GetUserByEmail_Call) Return(user *models.User, err error) *Storage_GetUserByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *Storage_GetUserByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*models.User, error)) *Storage_GetUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function for the type Storage
func (_mock *Storage) GetUserByID(ctx context.Context, userID uuid.UUID) (*models.User, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.User, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.User); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Storage_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type Storage_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *Storage_Expecter) GetUserByID(ctx interface{}, userID interface{}) *Storage_GetUserByID_Call {
	return &Storage_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, userID)}
}

func (_c *Storage_GetUserByID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *Storage_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Storage_GetUserByID_Call) Return(user *models.User, err error) *Storage_GetUserByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *Storage_GetUserByID_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (*models.User, error)) *Storage_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByUsername provides a mock function for the type Storage
func (_mock *Storage) GetUserByUsername(ctx context.Context, username string) (*models.User, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByUsername")
	}

	var r0 *models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.User, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = returnFunc(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Storage_GetUserByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByUsername'
type Storage_GetUserByUsername_Call struct {
	*mock.Call
}

// GetUserByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *Storage_Expecter) GetUserByUsername(ctx interface{}, username interface{}) *Storage_GetUserByUsername_Call {
	return &Storage_GetUserByUsername_Call{Call: _e.mock.On("GetUserByUsername", ctx, username)}
}

func (_c *Storage_GetUserByUsername_Call) Run(run func(ctx context.Context, username string)) *Storage_GetUserByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Storage_GetUserByUsername_Call) Return(user *models.User, err error) *Storage_GetUserByUsername_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *Storage_GetUserByUsername_Call) RunAndReturn(run func(ctx context.Context, username string) (*models.User, error)) *Storage_GetUserByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsers provides a mock function for the type Storage
func (_mock *Storage) GetUsers(ctx context.Context, page uint32, limit uint32) (*pagination.PaginationResponse[models.User], error) {
	ret := _mock.Called(ctx, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetUsers")
	}

	var r0 *pagination.PaginationResponse[models.User]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint32, uint32) (*pagination.PaginationResponse[models.User], error)); ok {
		return returnFunc(ctx, page, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint32, uint32) *pagination.PaginationResponse[models.User]); ok {
		r0 = returnFunc(ctx, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pagination.PaginationResponse[models.User])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint32, uint32) error); ok {
		r1 = returnFunc(ctx, page, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Storage_GetUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsers'
type Storage_GetUsers_Call struct {
	*mock.Call
}

// GetUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - page uint32
//   - limit uint32
func (_e *Storage_Expecter) GetUsers(ctx interface{}, page interface{}, limit interface{}) *Storage_GetUsers_Call {
	return &Storage_GetUsers_Call{Call: _e.mock.On("GetUsers", ctx, page, limit)}
}

func (_c *Storage_GetUsers_Call) Run(run func(ctx context.Context, page uint32, limit uint32)) *Storage_GetUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint32
		if args[1] != nil {
			arg1 = args[1].(uint32)
		}
		var arg2 uint32
		if args[2] != nil {
			arg2 = args[2].(uint32)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Storage_GetUsers_Call) Return(paginationResponse *pagination.PaginationResponse[models.User], err error) *Storage_GetUsers_Call {
	_c.Call.Return(paginationResponse, err)
	return _c
}

func (_c *Storage_GetUsers_Call) RunAndReturn(run func(ctx context.Context, page uint32, limit uint32) (*pagination.PaginationResponse[models.User], error)) *Storage_GetUsers_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function for the type Storage
func (_mock *Storage) UpdateUser(ctx context.Context, params *models.UpdateUserParams) (*models.User, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 *models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.UpdateUserParams) (*models.User, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.UpdateUserParams) *models.User); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *models.UpdateUserParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Storage_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type Storage_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - params *models.UpdateUserParams
func (_e *Storage_Expecter) UpdateUser(ctx interface{}, params interface{}) *Storage_UpdateUser_Call {
	return &Storage_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx, params)}
}

func (_c *Storage_UpdateUser_Call) Run(run func(ctx context.Context, params *models.UpdateUserParams)) *Storage_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.UpdateUserParams
		if args[1] != nil {
			arg1 = args[1].(*models.UpdateUserParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Storage_UpdateUser_Call) Return(user *models.User, err error) *Storage_UpdateUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *Storage_UpdateUser_Call) RunAndReturn(run func(ctx context.Context, params *models.UpdateUserParams) (*models.User, error)) *Storage_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}
