name: Monorepo CI/CD PR

run-name: ${{ github.event_name }} · ${{ github.ref_name }}

on:
  pull_request:

permissions:
  contents: read

jobs:
  backend:
    name: Backend API
    uses: ./.github/workflows/backend.yml

  admin:
    name: Admin Web
    uses: ./.github/workflows/admin.yml