name: Deploy food-swipe-backend to vps

on:
  push:
    branches:
      - feat/add-docker-workflow-for-food-swipe-backend

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/food-swipe
            export CR_PAT=YOUR_TOKEN
            echo $CR_PAT | docker login ghcr.io -u USERNAME --password-stdin
            docker pull ghcr.io/msvdaamen/food-swipe-backend:latest
