name: Deploy food-swipe-backend to vps

on:
  push:
    branches:
      - feat/add-docker-workflow-for-food-swipe-backend

jobs:
  deploy:
    needs: prepare-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/food-swipe
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

#            sudo docker compose -f docker-compose.prod.yaml up -d
